### ISSUE TITLE
pinv: Where is this function defined?

### ISSUE THREAD

**Issue by joftius** [selective-inference/R-software#16]
I was trying to run a simulation using fsInf with type="all" instead of type="active" and it uses a function "pinv" which I can't find anywhere in our repo.

**Comment by ryantibs** [comment]
It's in selectiveInference/R/funs.fixed.R

**Comment by joftius** [comment]
Ohhh, I see now that the github repository search only does this: "Showing the top two matches" for each file. So the search result wasn't showing the line where it's defined.

Perhaps this function and updateQR (in funs.lar) shoud be moved to funs.common?

**Comment by ryantibs** [comment]
Yes, I'm fine with them being moved
