### ISSUE TITLE
groupfs: AIC stop -- check known/unknown sigma

### ISSUE THREAD

**Issue by joftius** [selective-inference/R-software#4]

**Comment by tibshirani** [comment]
Translation ?

**Comment by joftius** [comment]
I am just using the "issues" feature of github to track things on my to-do
list. They're all on this page:
https://github.com/selective-inference/R-software/issues -- it's a nice
collaboration feature, for example if you notice a bug while using my code
you can create a new issue and "assign" it to me

In case by "translation" you were asking about this specific issue, I had
noticed in a simulation when I use the versions of forward stepwise where
\sigma is unknown, choose a model by AIC, and then estimate \sigma from
that model, then the T\chi p-values were very biased. So, once I finish the
truncated F for groups I will probably put a warning or something to make
sure people use the F test instead of chi with estimated \sigma
