### ISSUE TITLE
fixedLassoInf error: x cannot have duplicate columns

### ISSUE THREAD

**Issue by matteo-V** [selective-inference/R-software#48]
I receive an error that my matrix X has duplicated columns when using `fixedLassoInf`. I ran the `checkcols` function code in interactive mode and the columns returning `TRUE` change with each iteration — though the number is consistently two. 

The design matrix is not of full rank, is this the cause of the error? 

code reproduced below. 
```
betas = coef(lasso.fit, #from glmnet object
             s=lam/n, 
             exact = T, 
             x=as.matrix( illness_model_dat[,c(-1 )] ), 
             y=as.factor( illness_model_dat[,1] ))[-1] #[-1] removes the intercept
#perform inference for glmnet (LASSO) model
lasso.inference <- 
  fixedLassoInf(x = as.matrix( illness_model_dat[,-1] ),
                y = as.logical( illness_model_dat[,1] )*1 , 
                beta = betas, 
                lambda = lam, 
                family = 'binomial')
```

**Comment by ivananselmo7** [comment]
Hi!

Did someone manage to get this clear?

Thank you!
